#pragma once
#ifndef _MULTIPROJECT_PROJECT_CONFIG_H_
#define _MULTIPROJECT_PROJECT_CONFIG_H_

#define _COMPILE_WITHOUT_MULTIPROJECT false

#define _MULTIPROJECT_TIME_LIMIT 1000
#define _MULTIPROJECT_STACK_SIZE_MB 256

#define _RUN_WITHOUT_INPUT true

#define _USE_DEBUG true & _DEBUG

#endif // _MULTIPROJECT_PROJECT_CONFIG_H_
